vich_uploader:
  db_driver: orm

  metadata:
    type: attribute

  mappings:
    miniatures:
      uri_prefix: /images/miniatures
      upload_destination: '%kernel.project_dir%/public/images/miniatures'
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer