vich_uploader:
  db_driver: orm
  metadata:
    type: attribute
  mappings:
    photopr:
      uri_prefix: /images/photopr
      upload_destination: '%kernel.project_dir%/public/images/photopr'
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
      delete_on_update: true